name = input('What is your name? ')
print(f'Hello {name}')
color = input('What is your favorite color? ').lower()
print(f'{color} is a nice color')
print(f'{name} likes {color}')
birth_year = input('What year were you born? ')
print(type(birth_year))
age = 2025 - int(birth_year)
print(type(age))
print(f'You are {age} years old')
weight_lbs = input('What is your weight in pounds? ')
print(type(weight_lbs))
weight_kg = int(weight_lbs) * 0.454
print(f'You are {weight_kg} kg which is {weight_lbs} pounds')
